# Generated by Django 4.2.3 on 2023-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.FloatField()),
                ("alert_rating", models.FloatField()),
                ("alert_g_spread", models.FloatField()),
                ("alert_bm_spread", models.FloatField()),
                ("alert_ai", models.FloatField()),
                ("alert", models.FloatField()),
                ("total", models.FloatField()),
                ("region", models.FloatField()),
            ],
        ),
    ]
