# Generated by Django 4.2.3 on 2023-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_predict"),
    ]

    operations = [
        migrations.CreateModel(
            name="predict_a",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.CharField(max_length=100)),
                ("b", models.CharField(max_length=100)),
                ("c", models.FloatField()),
                ("d", models.FloatField()),
                ("e", models.FloatField()),
                ("f", models.FloatField()),
                ("g", models.FloatField()),
                ("h", models.FloatField()),
                ("i", models.FloatField()),
                ("j", models.FloatField()),
                ("k", models.FloatField()),
                ("l", models.FloatField()),
                ("m", models.FloatField()),
                ("n", models.FloatField()),
                ("o", models.FloatField()),
                ("p", models.FloatField()),
                ("q", models.FloatField()),
                ("r", models.FloatField()),
                ("s", models.FloatField()),
                ("t", models.FloatField()),
                ("u", models.FloatField()),
                ("v", models.FloatField()),
                ("w", models.FloatField()),
            ],
        ),
    ]
